### ISSUE TITLE
Crash Entering Neither on Dedicated Server

### ISSUE THREAD

**Issue by NoBodysProgramer** [NeosSkopos/ColoniesAndTechnologies#12]
Dedicated Server, when entering the neither for the first time I got these crashes back to back.
[crash-2024-06-01_21.50.09-server.txt](https://github.com/user-attachments/files/15523496/crash-2024-06-01_21.50.09-server.txt)
[crash-2024-06-01_21.49.06-server.txt](https://github.com/user-attachments/files/15523497/crash-2024-06-01_21.49.06-server.txt)

Only happened the first time I went to the neither and I am not having any other problems related to this issue.

**Comment by NeosSkopos** [comment]
I remember getting this in a different modpack before. (When I entered the end for the first time).
It has to do with the load on the server when generating that dimension for the first time.

You can prevent this from happening by going into the dedicated server's properties and changing **maxticktime** to 0.
That disables the ServerHangWatchdog from crashing the server and you'll just have to "wait it out" until the server generated your dimension. Fortunately it should only be a long load the first time.

Thanks for logging this! Haven't experienced this on our server, so good to know some do get this.
