### ISSUE TITLE
[Rendering] Arm animation differ from glove

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#2]
when a glove is equiped and you move around, the glove gets the walk animation movement, but the arm doesn't, creating an artifact where to gloves goes in and out of your skin

**Comment by Kiryonn** [comment]
PS: it wasn't happening in version 18 of the modpack

**Comment by NeosSkopos** [comment]
Hi there!
Thanks for reporting it.
Which version was this? Version 38?
Also, Are you talking about the Aether gloves? Or one of the gloves from the Artifacts mod?
I'm currently publishing version 39, which does fixes some graphical inconsistencies due to a recent upgrade in Sodium-Embeddium that I had to cater for while waiting for Oculus to also work with the latest Embeddium version. 

I checked version 39 now (before publishing it) and the gloves seem to be correct, so please let me know if this fixes it for you as well :).

**Comment by NeosSkopos** [comment]
Version 39 is now live. Please check if resolved.
If not, please let me know which trinket or Aether slot you used and which gloves.
Thanks :)

**Comment by Kiryonn** [comment]
thanks i'll check, sorry for the late answer but yes it was the version 38 and yes i was talking about the Aether gloves.

**Comment by Kiryonn** [comment]
I still have the issue no matter which Aether gloves i use.
![2024-02-01_19 01 24](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/2ebdd795-76d6-406c-8984-6276a5d2128a)

**Comment by Kiryonn** [comment]
do i need to remove some files to refresh the rendering ?

**Comment by NeosSkopos** [comment]
Where are you equipping them?
In the cloud section made for Aether trinkets?

**Comment by NeosSkopos** [comment]
Found a workaround:
Disable "View bobbing" in the video settings.
I'll still test this with using only the Aether mod and vanilla. Perhaps this is something they don't know about yet, so I'll log an issue with them as well after testing it without it being in a big pack and I'll publish version 40 of the modpack without view bobbing as a default config.

**Comment by NeosSkopos** [comment]
(Also keeping the issue open until I could find the cause - if this is something I can fix at all for View Bobbing and not something broken with the Aether mod internally.)

**Comment by Kiryonn** [comment]
> Where are you equipping them? In the cloud section made for Aether trinkets?

Yes

**Comment by Kiryonn** [comment]
> Found a workaround: Disable "View bobbing" in the video settings. I'll still test this with using only the Aether mod and vanilla. Perhaps this is something they don't know about yet, so I'll log an issue with them as well after testing it without it being in a big pack and I'll publish version 40 of the modpack without view bobbing as a default config.

I'll try that

**Comment by Kiryonn** [comment]
Well it works. Thought i don't have the animation anymore, at least i don't have that weird effect.

**Comment by NeosSkopos** [comment]
I'm busy testing for what might cause this.
The View Bobbing works fine with just the Aether mod, so there's some other mod that interferes with the hand animation somehow.

**Comment by Kiryonn** [comment]
> I'm busy testing for what might cause this.

I'm sorry to hear that because i still find new issues every 3 hours or so 😂

**Comment by NeosSkopos** [comment]
Dude, keep 'em coming!
I love knowing about these, because we haven't encountered any of these ourselves.
And usually, once I learn of something, I try fix/patch it if possible :).

**Comment by NeosSkopos** [comment]
I managed to find out that the switch from "A.V.A - Alliance of Valiant Arms Guns" to "A.V.A - Alliance of Valiant Arms Guns (Light)" has something to do with this. It stops the hand from moving during sprinting with view bobbing enabled.

**Comment by NeosSkopos** [comment]
Ticket logged with the mod: https://bitbucket.org/pelluciddice/ava/issues/102/ava-light-view-bobbing-not-working

**Comment by NeosSkopos** [comment]
Latest versions of the modpack replaced the AVA mod with Just Enough Guns, so this glitch is no longer an issue.

If, however, it still happens for some reason or with some interactions, the Aether mod allows you to hide its gloves in the slot where it's equipped. (there's a small visibility checkbox in that slot.)
