### ISSUE TITLE
[Minor] Unusable items

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#8]
- modpack version: 39

![2024-02-03_13 58 22](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/4c876f93-9013-4f6c-afab-1d95baea28c2)

**Comment by NeosSkopos** [comment]
Interesting.
I believe you probably got this one from a loot bag as well?
I'll think about this one - I can either add that mod, or add those items as blacklisted from the loot bags.

**Comment by Kiryonn** [comment]
> you probably got this one from a loot bag as well?

I sure did

**Comment by Kiryonn** [comment]
Something tells me there will be a lot more items that would need to be blacklisted.
Might be a good idea to go on a test world and open thousands of them to make sure nothing weird pops up.

**Comment by NeosSkopos** [comment]
That is true.
The best I can do for now though, is to blacklist patterns (e.g: everything with "creative" in it is already blacklisted), blacklist entire mods (and whitelist only the items from it that I deem as safe) and add individual items that I learn about from there on.

I'm currently working on this one.

If you ever find another invalid item, please let me know!
I really appreciate the inputs!

**Comment by Kiryonn** [comment]
I'd galdly do so when i play the modpack. Unfortunatly i had my days off this week so i had some time to lose. I'm afraid i won't be able to do so in the near future.

**Comment by NeosSkopos** [comment]
Should now be sorted - I chose to exclude the Simply Tools items.
Version 40 is now live :).

**Comment by NeosSkopos** [comment]
> I'd galdly do so when i play the modpack. Unfortunatly i had my days off this week so i had some time to lose. I'm afraid i won't be able to do so in the near future.

Thanks for the contributions(reports) made during this time anyways! :D
